on: [push]

name: Full check

jobs:
  build_and_test:
    name: Build and Test stripe-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo fmt -- --check
          make all
